config/routes.rb
Rails.application.routes.draw do
root "departments#index"
resources :departments do
  resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy] 
  
  def index
    @departments = Department.all
  end

  def show
    # render :show
  end

  def edit
    render partial: "form"
  end

  def update
    if @department.update(department_params)
      redirect_to departments_path
    else
     render partial: "form"
    end
  end

  def new
    @department = Department.new()
    render partial: "form"
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else
      render partial: "form"
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end

  private
  def set_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:name)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = @department.items
  end

  def show
  end

  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to department_item_path(@department.id, @item.id)
    else
      render partial: "form"
    end
  end

  def new
    @item = @department.items.new
    render partial: "form"
  end
  
  def create
    @item = @department.items.new(item_params)
    if @item.save
      redirect_to department_item_path(@department.id, @item.id)
    else 
      render partial: "form"
    end
  end

  def destroy
    @item.destroy
    redirect_to department_items_path(@department.id)
  end

# ============= PRIVATE METHODS ========================
  private
  def set_department
    @department = Department.find(params[:department_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :price, :in_stock)
  end


end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1><%= @department.id ? 'Edit Department Name' : 'Add New Department' %></h1>

<%= form_for @department do |f| %>
  <%= f.label :name%>
  <%= f.text_field :name %>
  <%= f.submit %>
<%end%>

app/views/departments/index.html.erb
<h1>Department Directory</h1>
<hr />
<%= link_to "Create New Department", new_department_path%>

<ul>
<% @departments.each do |department| %>
<li><%= link_to department.name, department_path(department.id) %></li>
<% end %>
</ul>

app/views/departments/show.html.erb
<h1>Viewing <%= @department.name %> Department Store Options </h2>
<hr>
<p>What would you like to do?</p>

<ul>
<li><%= link_to "View Items", department_items_path(@department.id) %></li>
<li><%= link_to "Edit Department Name", edit_department_path(@department.id) %></li>
<li><%= link_to "Delete Department", department_path(@department.id), method: :delete %></li>
<li><%= link_to "Back To Department Index", departments_path %></li>
</ul>

app/views/items/_form.html.erb
<h1> <%= @item.id ? "Edit Item" : "Create New Item" %>  </h1>
<hr />
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :price %>
  <%= f.text_field :price %>
  <br />
  <%= f.label :in_stock %>
  <%= f.text_field :in_stock %>
  <br />
  <%= f.submit %>
<% end %>

app/views/items/index.html.erb
<h1><%=@department.name%> Items</h1>
<hr>
<%= link_to "Add New Item", new_department_item_path(@department.id)%>

<ul>
<% @items.each do |item| %>
<li><%= link_to item.name, department_item_path(@department.id, item.id)%></li>
<%end%>
</ul>

<%= link_to "Back To Department Menu", department_path(@department.id)%>

app/views/items/show.html.erb
<h3><%=@item.name%></h3>
<hr />
<h4> Price: $<%= @item.price%> </h4>
<h4> In Stock: <%= @item.in_stock == true ? "Yes" : "No" %> </h4>
<br>
<%= link_to "Edit Item Details", edit_department_item_path(@department.id, @item.id)%>
<br>
<%= link_to "Back To Items List", department_items_path(@department.id)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>